starting_edit_select_mode = "Fire TYPE"

starting_edit_mode = {
    {
        name = "start_with_all_perks",
        perks = {
            "CRITICAL_HIT",
            "BREATH_UNDERWATER",
            "EXTRA_MONEY",
            "EXTRA_MONEY_TRICK_KILL",
            "HOVER_BOOST",
            "MOVEMENT_FASTER",
            "LOW_GRAVITY",
            "SPEED_DIVER",
            "STRONG_KICK",
            "REPELLING_CAPE",
            "EXPLODING_CORPSES",
            "SAVING_GRACE",
            "INVISIBILITY",
            "GLOBAL_GORE",
            "REMOVE_FOG_OF_WAR",
            "VAMPIRISM",
            "EXTRA_HP",
            "HEARTS_MORE_EXTRA_HP",
            "GLASS_CANNON",
            "RESPAWN",
            "WORM_ATTRACTOR",
            "WORM_DETRACTOR",
            "PROTECTION_FIRE",
            "PROTECTION_RADIOACTIVITY",
            "PROTECTION_EXPLOSION",
            "PROTECTION_MELEE",
            "PROTECTION_ELECTRICITY",
            "TELEPORTITIS",
            "STAINLESS_ARMOUR",
            "EDIT_WANDS_EVERYWHERE",
            "ABILITY_ACTIONS_MATERIALIZED",
            "PROJECTILE_HOMING",
            "PROJECTILE_HOMING_SHOOTER",
            "FREEZE_FIELD",
            "DISSOLVE_POWDERS",
            "BLEED_SLIME",
            "BLEED_OIL",
            "SHIELD",
            "REVENGE_EXPLOSION",
            "REVENGE_TENTACLE",
            "ATTACK_FOOT",
            "PLAGUE_RATS",
            "PROJECTILE_REPULSION",
            "ELECTRICITY",
            "ATTRACT_ITEMS",
            "EXTRA_KNOCKBACK",
            "LOWER_SPREAD",
            "BOUNCE",
            "EXTRA_PERK",
            "PERKS_LOTTERY",
            "GENOME_MORE_HATRED",
            "GENOME_MORE_LOVE",
        },
    },
    {
        name = "start_with_a_random_perk",
        perks = {
            "random",
        },
    },
    {
        name = "start_with_edit_wands_everywhere",
        perks = {
            "EDIT_WANDS_EVERYWHERE",
        },
    },
}
